### ISSUE TITLE
EPIC: Verplaatsen Tribe naar nieuwe LZ

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/tribe-brp-linker#82]
- [x] DNS-managementproject voorbereiden
- [x] #84
- [x] #88
- [x] #106
- [x] #107

**Comment by joostvanderborg** [comment]
dev is verhuisd en werkt. accp-account aangemaakt, nog niet helemaal geprovisioned.

**Comment by joostvanderborg** [comment]
Accp wacht op toestemming om cloudfront-resources te maken.

**Comment by wvdeeckhout** [comment]
@joostvanderborg bekijkt deze

**Comment by joostvanderborg** [comment]
Nieuwe issues aangemaakt voor verhuizing acceptatie- en productieomgeving.

**Comment by marnixdessing** [comment]
Heropend en epic van gemaakt met nog een issue dat gedaan moet worden.

**Comment by joostvanderborg** [comment]
Verhuisd, nieuw issue aangemaakt om volgende sprint oude omgeving op te ruimen.
